#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WSAndroid.Resource", IsApplication=true)]

namespace WSAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int Boton1 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int Boton2 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int Boton3 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int Boton4 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int Boton5 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int Boton6 = 2131034138;
			
			// aapt resource value: 0x7f050013
			public const int cmdBoton1 = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int cmdComenzar = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int gridLayout1 = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int llhBajada = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int llhEstadoConexion = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int llhFuerzaSeñal = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int llhSubida = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int llhTipoConexion = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int llvPrincipal = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int txtBajada = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int txtConexion = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int txtFuerzaSenalMobile = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int txtResulBajada = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int txtResulConexion = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int txtResulFuerzaSenalMobile = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int txtResulNombreConexion = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int txtResulSubida = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int txtResulTipoConexion = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int txtSubida = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int txtTestVelocidad = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int txtTipoConexion = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConexionInet = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Principal = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int Bajada = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int Comenzar = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int Conectado = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int ConexionInet = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int FUERZASENALMOBILE = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int MOBILE = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int NoConectado = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Subida = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int TIPOCONEXION = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int TestVelocidad = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int WIFI = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
