//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WSAndroid.SageX3WS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CAdxWebServiceXmlCCSoapBinding", Namespace="http://www.adonix.com/WSS")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CAdxParamKeyValue))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CAdxMessage))]
    public partial class CAdxWebServiceXmlCCService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback runOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback readOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback modifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback actionObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback actionObject1OperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDataXmlSchemaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CAdxWebServiceXmlCCService() {
            this.Url = "http://176.58.9.37:28880/adxwsvc/services/CAdxWebServiceXmlCC";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event runCompletedEventHandler runCompleted;
        
        /// <remarks/>
        public event saveCompletedEventHandler saveCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event readCompletedEventHandler readCompleted;
        
        /// <remarks/>
        public event queryCompletedEventHandler queryCompleted;
        
        /// <remarks/>
        public event getDescriptionCompletedEventHandler getDescriptionCompleted;
        
        /// <remarks/>
        public event modifyCompletedEventHandler modifyCompleted;
        
        /// <remarks/>
        public event actionObjectCompletedEventHandler actionObjectCompleted;
        
        /// <remarks/>
        public event actionObject1CompletedEventHandler actionObject1Completed;
        
        /// <remarks/>
        public event deleteLinesCompletedEventHandler deleteLinesCompleted;
        
        /// <remarks/>
        public event insertLinesCompletedEventHandler insertLinesCompleted;
        
        /// <remarks/>
        public event getDataXmlSchemaCompletedEventHandler getDataXmlSchemaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("runReturn")]
        public CAdxResultXml run(CAdxCallContext callContext, string publicName, string inputXml) {
            object[] results = this.Invoke("run", new object[] {
                        callContext,
                        publicName,
                        inputXml});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void runAsync(CAdxCallContext callContext, string publicName, string inputXml) {
            this.runAsync(callContext, publicName, inputXml, null);
        }
        
        /// <remarks/>
        public void runAsync(CAdxCallContext callContext, string publicName, string inputXml, object userState) {
            if ((this.runOperationCompleted == null)) {
                this.runOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunOperationCompleted);
            }
            this.InvokeAsync("run", new object[] {
                        callContext,
                        publicName,
                        inputXml}, this.runOperationCompleted, userState);
        }
        
        private void OnrunOperationCompleted(object arg) {
            if ((this.runCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runCompleted(this, new runCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("saveReturn")]
        public CAdxResultXml save(CAdxCallContext callContext, string publicName, string objectXml) {
            object[] results = this.Invoke("save", new object[] {
                        callContext,
                        publicName,
                        objectXml});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void saveAsync(CAdxCallContext callContext, string publicName, string objectXml) {
            this.saveAsync(callContext, publicName, objectXml, null);
        }
        
        /// <remarks/>
        public void saveAsync(CAdxCallContext callContext, string publicName, string objectXml, object userState) {
            if ((this.saveOperationCompleted == null)) {
                this.saveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveOperationCompleted);
            }
            this.InvokeAsync("save", new object[] {
                        callContext,
                        publicName,
                        objectXml}, this.saveOperationCompleted, userState);
        }
        
        private void OnsaveOperationCompleted(object arg) {
            if ((this.saveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveCompleted(this, new saveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("deleteReturn")]
        public CAdxResultXml delete(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys) {
            object[] results = this.Invoke("delete", new object[] {
                        callContext,
                        publicName,
                        objectKeys});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys) {
            this.deleteAsync(callContext, publicName, objectKeys, null);
        }
        
        /// <remarks/>
        public void deleteAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        callContext,
                        publicName,
                        objectKeys}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("readReturn")]
        public CAdxResultXml read(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys) {
            object[] results = this.Invoke("read", new object[] {
                        callContext,
                        publicName,
                        objectKeys});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void readAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys) {
            this.readAsync(callContext, publicName, objectKeys, null);
        }
        
        /// <remarks/>
        public void readAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, object userState) {
            if ((this.readOperationCompleted == null)) {
                this.readOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreadOperationCompleted);
            }
            this.InvokeAsync("read", new object[] {
                        callContext,
                        publicName,
                        objectKeys}, this.readOperationCompleted, userState);
        }
        
        private void OnreadOperationCompleted(object arg) {
            if ((this.readCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.readCompleted(this, new readCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("queryReturn")]
        public CAdxResultXml query(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, int listSize) {
            object[] results = this.Invoke("query", new object[] {
                        callContext,
                        publicName,
                        objectKeys,
                        listSize});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void queryAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, int listSize) {
            this.queryAsync(callContext, publicName, objectKeys, listSize, null);
        }
        
        /// <remarks/>
        public void queryAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, int listSize, object userState) {
            if ((this.queryOperationCompleted == null)) {
                this.queryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryOperationCompleted);
            }
            this.InvokeAsync("query", new object[] {
                        callContext,
                        publicName,
                        objectKeys,
                        listSize}, this.queryOperationCompleted, userState);
        }
        
        private void OnqueryOperationCompleted(object arg) {
            if ((this.queryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCompleted(this, new queryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("getDescriptionReturn")]
        public CAdxResultXml getDescription(CAdxCallContext callContext, string publicName) {
            object[] results = this.Invoke("getDescription", new object[] {
                        callContext,
                        publicName});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void getDescriptionAsync(CAdxCallContext callContext, string publicName) {
            this.getDescriptionAsync(callContext, publicName, null);
        }
        
        /// <remarks/>
        public void getDescriptionAsync(CAdxCallContext callContext, string publicName, object userState) {
            if ((this.getDescriptionOperationCompleted == null)) {
                this.getDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDescriptionOperationCompleted);
            }
            this.InvokeAsync("getDescription", new object[] {
                        callContext,
                        publicName}, this.getDescriptionOperationCompleted, userState);
        }
        
        private void OngetDescriptionOperationCompleted(object arg) {
            if ((this.getDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDescriptionCompleted(this, new getDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("modifyReturn")]
        public CAdxResultXml modify(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, string objectXml) {
            object[] results = this.Invoke("modify", new object[] {
                        callContext,
                        publicName,
                        objectKeys,
                        objectXml});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void modifyAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, string objectXml) {
            this.modifyAsync(callContext, publicName, objectKeys, objectXml, null);
        }
        
        /// <remarks/>
        public void modifyAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, string objectXml, object userState) {
            if ((this.modifyOperationCompleted == null)) {
                this.modifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodifyOperationCompleted);
            }
            this.InvokeAsync("modify", new object[] {
                        callContext,
                        publicName,
                        objectKeys,
                        objectXml}, this.modifyOperationCompleted, userState);
        }
        
        private void OnmodifyOperationCompleted(object arg) {
            if ((this.modifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modifyCompleted(this, new modifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("actionObjectReturn")]
        public CAdxResultXml actionObject(CAdxCallContext callContext, string publicName, string actionCode, string objectXml) {
            object[] results = this.Invoke("actionObject", new object[] {
                        callContext,
                        publicName,
                        actionCode,
                        objectXml});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void actionObjectAsync(CAdxCallContext callContext, string publicName, string actionCode, string objectXml) {
            this.actionObjectAsync(callContext, publicName, actionCode, objectXml, null);
        }
        
        /// <remarks/>
        public void actionObjectAsync(CAdxCallContext callContext, string publicName, string actionCode, string objectXml, object userState) {
            if ((this.actionObjectOperationCompleted == null)) {
                this.actionObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactionObjectOperationCompleted);
            }
            this.InvokeAsync("actionObject", new object[] {
                        callContext,
                        publicName,
                        actionCode,
                        objectXml}, this.actionObjectOperationCompleted, userState);
        }
        
        private void OnactionObjectOperationCompleted(object arg) {
            if ((this.actionObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actionObjectCompleted(this, new actionObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="actionObject1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("actionObjectReturn")]
        public CAdxResultXml actionObject(CAdxCallContext callContext, string publicName, string actionCode, CAdxParamKeyValue[] objectKeys) {
            object[] results = this.Invoke("actionObject1", new object[] {
                        callContext,
                        publicName,
                        actionCode,
                        objectKeys});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void actionObject1Async(CAdxCallContext callContext, string publicName, string actionCode, CAdxParamKeyValue[] objectKeys) {
            this.actionObject1Async(callContext, publicName, actionCode, objectKeys, null);
        }
        
        /// <remarks/>
        public void actionObject1Async(CAdxCallContext callContext, string publicName, string actionCode, CAdxParamKeyValue[] objectKeys, object userState) {
            if ((this.actionObject1OperationCompleted == null)) {
                this.actionObject1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnactionObject1OperationCompleted);
            }
            this.InvokeAsync("actionObject1", new object[] {
                        callContext,
                        publicName,
                        actionCode,
                        objectKeys}, this.actionObject1OperationCompleted, userState);
        }
        
        private void OnactionObject1OperationCompleted(object arg) {
            if ((this.actionObject1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actionObject1Completed(this, new actionObject1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("deleteLinesReturn")]
        public CAdxResultXml deleteLines(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, string blocKey, string[] lineKeys) {
            object[] results = this.Invoke("deleteLines", new object[] {
                        callContext,
                        publicName,
                        objectKeys,
                        blocKey,
                        lineKeys});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void deleteLinesAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, string blocKey, string[] lineKeys) {
            this.deleteLinesAsync(callContext, publicName, objectKeys, blocKey, lineKeys, null);
        }
        
        /// <remarks/>
        public void deleteLinesAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, string blocKey, string[] lineKeys, object userState) {
            if ((this.deleteLinesOperationCompleted == null)) {
                this.deleteLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteLinesOperationCompleted);
            }
            this.InvokeAsync("deleteLines", new object[] {
                        callContext,
                        publicName,
                        objectKeys,
                        blocKey,
                        lineKeys}, this.deleteLinesOperationCompleted, userState);
        }
        
        private void OndeleteLinesOperationCompleted(object arg) {
            if ((this.deleteLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteLinesCompleted(this, new deleteLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("insertLinesReturn")]
        public CAdxResultXml insertLines(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, string blocKey, string lineKey, string lineXml) {
            object[] results = this.Invoke("insertLines", new object[] {
                        callContext,
                        publicName,
                        objectKeys,
                        blocKey,
                        lineKey,
                        lineXml});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void insertLinesAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, string blocKey, string lineKey, string lineXml) {
            this.insertLinesAsync(callContext, publicName, objectKeys, blocKey, lineKey, lineXml, null);
        }
        
        /// <remarks/>
        public void insertLinesAsync(CAdxCallContext callContext, string publicName, CAdxParamKeyValue[] objectKeys, string blocKey, string lineKey, string lineXml, object userState) {
            if ((this.insertLinesOperationCompleted == null)) {
                this.insertLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertLinesOperationCompleted);
            }
            this.InvokeAsync("insertLines", new object[] {
                        callContext,
                        publicName,
                        objectKeys,
                        blocKey,
                        lineKey,
                        lineXml}, this.insertLinesOperationCompleted, userState);
        }
        
        private void OninsertLinesOperationCompleted(object arg) {
            if ((this.insertLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertLinesCompleted(this, new insertLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.adonix.com/WSS", ResponseNamespace="http://www.adonix.com/WSS")]
        [return: System.Xml.Serialization.SoapElementAttribute("getDataXmlSchemaReturn")]
        public CAdxResultXml getDataXmlSchema(CAdxCallContext callContext, string publicName) {
            object[] results = this.Invoke("getDataXmlSchema", new object[] {
                        callContext,
                        publicName});
            return ((CAdxResultXml)(results[0]));
        }
        
        /// <remarks/>
        public void getDataXmlSchemaAsync(CAdxCallContext callContext, string publicName) {
            this.getDataXmlSchemaAsync(callContext, publicName, null);
        }
        
        /// <remarks/>
        public void getDataXmlSchemaAsync(CAdxCallContext callContext, string publicName, object userState) {
            if ((this.getDataXmlSchemaOperationCompleted == null)) {
                this.getDataXmlSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDataXmlSchemaOperationCompleted);
            }
            this.InvokeAsync("getDataXmlSchema", new object[] {
                        callContext,
                        publicName}, this.getDataXmlSchemaOperationCompleted, userState);
        }
        
        private void OngetDataXmlSchemaOperationCompleted(object arg) {
            if ((this.getDataXmlSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDataXmlSchemaCompleted(this, new getDataXmlSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.adonix.com/WSS")]
    public partial class CAdxCallContext {
        
        private string codeLangField;
        
        private string codeUserField;
        
        private string passwordField;
        
        private string poolAliasField;
        
        private string poolIdField;
        
        private string requestConfigField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codeLang {
            get {
                return this.codeLangField;
            }
            set {
                this.codeLangField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codeUser {
            get {
                return this.codeUserField;
            }
            set {
                this.codeUserField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string poolAlias {
            get {
                return this.poolAliasField;
            }
            set {
                this.poolAliasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string poolId {
            get {
                return this.poolIdField;
            }
            set {
                this.poolIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string requestConfig {
            get {
                return this.requestConfigField;
            }
            set {
                this.requestConfigField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.adonix.com/WSS")]
    public partial class CAdxParamKeyValue {
        
        private string keyField;
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.adonix.com/WSS")]
    public partial class CAdxTechnicalInfos {
        
        private bool busyField;
        
        private bool changeLanguageField;
        
        private bool changeUserIdField;
        
        private bool flushAdxField;
        
        private double loadWebsDurationField;
        
        private int nbDistributionCycleField;
        
        private double poolDistribDurationField;
        
        private int poolEntryIdxField;
        
        private double poolExecDurationField;
        
        private double poolRequestDurationField;
        
        private double poolWaitDurationField;
        
        private string processReportField;
        
        private int processReportSizeField;
        
        private bool reloadWebsField;
        
        private bool resumitAfterDBOpenField;
        
        private int rowInDistribStackField;
        
        private double totalDurationField;
        
        private string traceRequestField;
        
        private int traceRequestSizeField;
        
        /// <comentarios/>
        public bool busy {
            get {
                return this.busyField;
            }
            set {
                this.busyField = value;
            }
        }
        
        /// <comentarios/>
        public bool changeLanguage {
            get {
                return this.changeLanguageField;
            }
            set {
                this.changeLanguageField = value;
            }
        }
        
        /// <comentarios/>
        public bool changeUserId {
            get {
                return this.changeUserIdField;
            }
            set {
                this.changeUserIdField = value;
            }
        }
        
        /// <comentarios/>
        public bool flushAdx {
            get {
                return this.flushAdxField;
            }
            set {
                this.flushAdxField = value;
            }
        }
        
        /// <comentarios/>
        public double loadWebsDuration {
            get {
                return this.loadWebsDurationField;
            }
            set {
                this.loadWebsDurationField = value;
            }
        }
        
        /// <comentarios/>
        public int nbDistributionCycle {
            get {
                return this.nbDistributionCycleField;
            }
            set {
                this.nbDistributionCycleField = value;
            }
        }
        
        /// <comentarios/>
        public double poolDistribDuration {
            get {
                return this.poolDistribDurationField;
            }
            set {
                this.poolDistribDurationField = value;
            }
        }
        
        /// <comentarios/>
        public int poolEntryIdx {
            get {
                return this.poolEntryIdxField;
            }
            set {
                this.poolEntryIdxField = value;
            }
        }
        
        /// <comentarios/>
        public double poolExecDuration {
            get {
                return this.poolExecDurationField;
            }
            set {
                this.poolExecDurationField = value;
            }
        }
        
        /// <comentarios/>
        public double poolRequestDuration {
            get {
                return this.poolRequestDurationField;
            }
            set {
                this.poolRequestDurationField = value;
            }
        }
        
        /// <comentarios/>
        public double poolWaitDuration {
            get {
                return this.poolWaitDurationField;
            }
            set {
                this.poolWaitDurationField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string processReport {
            get {
                return this.processReportField;
            }
            set {
                this.processReportField = value;
            }
        }
        
        /// <comentarios/>
        public int processReportSize {
            get {
                return this.processReportSizeField;
            }
            set {
                this.processReportSizeField = value;
            }
        }
        
        /// <comentarios/>
        public bool reloadWebs {
            get {
                return this.reloadWebsField;
            }
            set {
                this.reloadWebsField = value;
            }
        }
        
        /// <comentarios/>
        public bool resumitAfterDBOpen {
            get {
                return this.resumitAfterDBOpenField;
            }
            set {
                this.resumitAfterDBOpenField = value;
            }
        }
        
        /// <comentarios/>
        public int rowInDistribStack {
            get {
                return this.rowInDistribStackField;
            }
            set {
                this.rowInDistribStackField = value;
            }
        }
        
        /// <comentarios/>
        public double totalDuration {
            get {
                return this.totalDurationField;
            }
            set {
                this.totalDurationField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string traceRequest {
            get {
                return this.traceRequestField;
            }
            set {
                this.traceRequestField = value;
            }
        }
        
        /// <comentarios/>
        public int traceRequestSize {
            get {
                return this.traceRequestSizeField;
            }
            set {
                this.traceRequestSizeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.adonix.com/WSS")]
    public partial class CAdxMessage {
        
        private string messageField;
        
        private string typeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.adonix.com/WSS")]
    public partial class CAdxResultXml {
        
        private CAdxMessage[] messagesField;
        
        private string resultXmlField;
        
        private int statusField;
        
        private CAdxTechnicalInfos technicalInfosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public CAdxMessage[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string resultXml {
            get {
                return this.resultXmlField;
            }
            set {
                this.resultXmlField = value;
            }
        }
        
        /// <comentarios/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public CAdxTechnicalInfos technicalInfos {
            get {
                return this.technicalInfosField;
            }
            set {
                this.technicalInfosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void runCompletedEventHandler(object sender, runCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class runCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal runCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void saveCompletedEventHandler(object sender, saveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void readCompletedEventHandler(object sender, readCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class readCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal readCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void queryCompletedEventHandler(object sender, queryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void getDescriptionCompletedEventHandler(object sender, getDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void modifyCompletedEventHandler(object sender, modifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void actionObjectCompletedEventHandler(object sender, actionObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actionObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actionObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void actionObject1CompletedEventHandler(object sender, actionObject1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actionObject1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actionObject1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void deleteLinesCompletedEventHandler(object sender, deleteLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void insertLinesCompletedEventHandler(object sender, insertLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void getDataXmlSchemaCompletedEventHandler(object sender, getDataXmlSchemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDataXmlSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDataXmlSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CAdxResultXml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CAdxResultXml)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591